### PR TITLE
- #(371) Bracket matching doesn't move cursor if off screen

### PR DESCRIPTION
**Pull request by stevenaz**
- Fixed this item
         - Also fixed lockup if your cursor was to the right of the
close )
         
- #(enh - 105) Bracket matching - selection of text within brackets
         - Implemented... easy enough to take out if not requested

### CODE REVIEW

**Comment by mballance** [comment]
Hi Steven,
    After looking at this, I'd like to suggest the selection behavior be changed to be an optional add-on, rather than default behavior. CTRL+SHIFT+P is defined as 'Goto Matching Brace'. At least in my experiments, CTRL+SHIFT+P always selects the text leading up to the next brace -- which seems a bit of an undesired side-effect in some cases. Do you see the same thing on your side?

Thanks,
Matthew

**Comment by stevenaz** [comment]
Hi Matt,

I didn't see that, but please go ahead and disable it completely. I don't
feel that strongly about it.

If you send me a code snippet I will figure out what I did wrong and check
in a fix this week sometime.

Steven

**Comment by stevenaz** [comment]
Just realized that was a lousy email I sent asking you to fix my mess...
Please revert the change, or skip the merge and I will take care of it this
week.

I shouldn't have asked you to take it out, not your fault it is in there.

Regards,
Steven

**Comment by mballance** [comment]
Hi Steven,
    Okay, that's what I figured. If I place the cursor on the first character of 'class' in the code snippet below with no characters selected, then hit CTRL+SHIFT+P, the characters from 'cls1' to 'endclass' are selected ('class' is excluded). I am doing this on Windows. Not sure if that has an impact.

class cls1;

	function new();

	endfunction


endclass

**Comment by mballance** [comment]
No worries, Steven. I've commented out the line that enables selection for now. Everything else appears to work. 

-Matthew

**Comment by stevenaz** [comment]
Hi Matthew,

The behavior you saw was indended (except possibly that I should have
included the "class" as part of the selected code.  In the past I have
worked with editors that didn't just jump to the matching brace, but also
selected the code between the two braces.  When you have a long bit of code
between braces, it allows you to scroll up through the code and easily see
where the block starts / ends, without having to remember line numbers.

In the example you showed, the SVCharacterPairMatcher.java, gives you the
visual start / end points.  I haven't seen a better way of doing this.
Tweaking your example, Ctrl+Shift+P near the (.

This has to do with the enhancement request below.

105 <https://sourceforge.net/p/sveditor/feature-requests/105/> Bracket
matching - selection of text within brackets
<https://sourceforge.net/p/sveditor/feature-requests/105/>


Steven


class cls1;

    function new(
        input logic a
// assume the brace below is off-screen
        );

    endfunction

endclass

**Comment by mballance** [comment]
Hi Steven,
    I've been thinking about this more today. What if we used information
about the current selection to determine whether to select text or just
move the cursor? The current selection is available to the Goto Matching
Brace action. If the selection is non-zero in length (ie some text is
selected), the Goto Matching Brace action could extend that selection.
Otherwise (no text selected), it would just move the cursor. What do you
think? The one downside I can think of is that the user would need to
select at least one character before hitting CTRL+SHIFT+P.

Thanks,
Matthew

**Comment by stevenaz** [comment]
Good idea. That said, that might push up the maintenance effort having to
explain why there is different behavior.  I really do think that keeping
the sve behavior as close to the native eclipse behavior as possible is a
really good thing.

While once in a while the plug in may lose the occasional nice to have
feature, it probably isn't worth the getting the perception that this is a
non standard ide interface.

Steven

**Pull request merged**
